#!/bin/bash

theme="$HOME/.config/rofi/clipboard"

if ! command -v cliphist >/dev/null 2>&1; then
  notify-send "Program not found" "Make sure you have installed cliphist"
  exit 1
else
  cliphist list | rofi -dmenu -theme ${theme}.rasi | cliphist decode | wl-copy
fi
