#!/usr/bin/env bash

## Author  : Aditya Shakya (adi1090x)
## Github  : @adi1090x
#
## Applets : Screenshot

# Import Current Theme
theme="$HOME/.config/rofi/screenshot"

# Theme Elements
mesg="DIR: $(xdg-user-dir PICTURES)/Screenshots"

list_col='4'
list_row='1'
win_width='600px'

# Options
option_1=""
option_2=""
option_3=""
option_4="5s"

# Rofi CMD
rofi_cmd() {
  rofi -theme-str "window {width: $win_width;}" \
    -theme-str "listview {columns: $list_col; lines: $list_row;}" \
    -dmenu \
    -mesg "$mesg" \
    -markup-rows \
    -theme ${theme}.rasi
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "$option_1\n$option_2\n$option_3\n$option_4" | rofi_cmd
}

# Screenshot
time=$(date +%Y-%m-%d-%H-%M-%S)
geometry=$(xrandr | grep 'current' | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current')
dir="$(xdg-user-dir PICTURES)/Screenshots"
file="Screenshot_${time}_${geometry}.png"

if [[ ! -d "$dir" ]]; then
  mkdir -p "$dir"
fi

# notify and view screenshot
notify_view() {
  if [[ -e "$dir/$file" ]]; then
    notify-send -i $dir/$file -u low "Screenshot Saved."
  else
    notify-send -i $dir/$file -u low "Screenshot Deleted."
  fi
}

# countdown
countdown() {
  for sec in $(seq $1 -1 1); do
    notify-send -t 1000 "Taking shot in : $sec"
    sleep 2
  done
}

# take shots
shotnow() {
  cd ${dir} && sleep 1 && grim - | tee "$file" | wl-copy
  notify_view
}

shot5() {
  countdown '5'
  cd ${dir} && grim - | tee "$file" | wl-copy
  notify_view
}

shotwin() {
  w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
  w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
  cd ${dir} && sleep 0.5 && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
  notify_view
}

shotarea() {
  cd ${dir} && grim -g "$(slurp -b 24273acc -c a6da95ff -s cad3f50d -w 2 && sleep 1)" - | tee "$file" | wl-copy
  notify_view
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    shotnow
  elif [[ "$1" == '--opt2' ]]; then
    shotarea
  elif [[ "$1" == '--opt3' ]]; then
    shotwin
  elif [[ "$1" == '--opt4' ]]; then
    shot5
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
  run_cmd --opt1
  ;;
$option_2)
  run_cmd --opt2
  ;;
$option_3)
  run_cmd --opt3
  ;;
$option_4)
  run_cmd --opt4
  ;;
esac
