"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 3600000

format = """
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$python\
$cmd_duration\
$status\
$line_break\
$character\
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
format = '[  ](bg:blue fg:base)[ $path ](bg:surface0 fg:text)'
home_symbol = "~"
truncation_symbol = "…/"
truncation_length = 3

[git_branch]
symbol = ""
format = '[  ](bold text)[ $symbol ](bg:teal fg:base)[ $branch ](bg:surface0 fg:text)'
only_attached = true
always_show_remote = false
disabled = false

[git_status]
format = '[($ahead_behind)($all_status)](fg:teal bg:surface0)'
stashed = "*${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
up_to_date = " "
diverged = "⇡${ahead_count} ⇣${behind_count} "
conflicted = "=${count} "
deleted = "×${count} "
renamed = "»${count} "
modified = "!${count} "
staged = "+${count} "
untracked = "?${count} "
ignore_submodules = false

[nodejs]
symbol = ""
format = '[  ](bold text)[ $symbol ](bg:green fg:mantle)[ $version ](bg:surface0 fg:text)'

[c]
symbol = ""
format = '[  ](bold text)[ $symbol ](bg: fg:mantle)[ $version ](bg:surface0 fg:text)'

[rust]
symbol = "󱘗"
format = '[  ](bold text)[ $symbol ](bg:maroon fg:mantle)[ $version ](bg:surface0 fg:text)'

[golang]
symbol = "󰟓"
format = '[  ](bold text)[ $symbol ](bg:sapphire fg:mantle)[ $version ](bg:surface0 fg:text)'

[php]
symbol = ""
format = '[  ](bold text)[ $symbol ](bg:mauve fg:mantle)[ $version ](bg:surface0 fg:text)'

[java]
symbol = ""
format = '[  ](bold text)[ $symbol ](bg:green fg:mantle)[ $version ](bg:surface0 fg:text)'

[python]
symbol = ""
format = '[  ](bold text)[ $symbol ](bg:green fg:mantle)[ $version ](bg:surface0 fg:text)'
version_format = '${raw}'

[cmd_duration]
min_time = 2000
format = '[  ](bold text)[ 󱫑 ](bg:flamingo fg:mantle)[ $duration ](bg:surface0 fg:text)'
show_milliseconds = false

[status]
disabled = false
format = '[  ](bold text)[ $symbol ](bg:red fg:mantle)[( $common_meaning)( $signal_name) ](bg:surface0 fg:red)'
map_symbol = true
pipestatus = true
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = '󰂭'
not_found_symbol = '󰍉'
sigint_symbol = '󰐊'
signal_symbol = '󱐋'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯❯❯](bold fg:green)'
error_symbol = '[❯❯❯](bold fg:red)'
vimcmd_symbol = '[❮❮❮](bold fg:mauve)'
