"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 3600000

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$status\
$line_break\
$character\
"""

[directory]
format = '[](bold fg:purple)[ $path ]($style)[](bold fg:purple)'
style = "bg:purple fg:black"
home_symbol = " "
truncation_symbol = "••/"
truncation_length = 3

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "

[git_branch]
symbol = ""
format = '[ • ](bold fg:red)[](bold fg:green)[ $branch ]($style)'
style = "bold bg:green fg:black"
only_attached = true
always_show_remote = false
disabled = false

[git_status]
format = '[($ahead_behind)($all_status)](bg:green fg:black)[](bold fg:green)'
stashed = "*${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
up_to_date = " "
diverged = "⇡${ahead_count} ⇣${behind_count} "
conflicted = "=${count} "
deleted = "×${count} "
renamed = "»${count} "
modified = "!${count} "
staged = "+${count} "
untracked = "?${count} "
ignore_submodules = false

[cmd_duration]
min_time = 1000
format = '[ • ](bold red)[](bold fg:yellow)[ 󱫑 $duration ]($style)[](bold fg:yellow)'
style = "bg:yellow fg:black"
show_milliseconds = false

[status]
disabled = false
format = '[ • ](bold red)[](bold fg:red)[ $symbol ]($style)[($common_meaning)($signal_name) ]($style)[](bold fg:red)'
style = "bg:red fg:black"
map_symbol = true
pipestatus = true
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = '󰂭'
not_found_symbol = '󰍉'
sigint_symbol = '󰐊'
signal_symbol = '󱐋'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[󱞪](bold fg:green)"
error_symbol = "[󱞪](bold fg:red)"
