"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 3600000

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$status\
$line_break\
$character\
"""

palette = 'rose-pine'

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'

[directory]
format = '[  ](bg:gold fg:overlay)[ $path ](bg:overlay)'
home_symbol = "~"
truncation_symbol = "…/"
truncation_length = 3

[git_branch]
symbol = ""
format = '[ ❯ ](bold text)[ $symbol ](bg:pine fg:overlay)[ $branch ](bg:overlay)'
only_attached = true
always_show_remote = false
disabled = false

[git_status]
format = '[($ahead_behind)($all_status)](fg:foam bg:overlay)'
stashed = "*${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
up_to_date = " "
diverged = "⇡${ahead_count} ⇣${behind_count} "
conflicted = "=${count} "
deleted = "×${count} "
renamed = "»${count} "
modified = "!${count} "
staged = "+${count} "
untracked = "?${count} "
ignore_submodules = false

[cmd_duration]
min_time = 2000
format = '[ ❯ ](bold text)[ 󱫑 ](bg:rose fg:overlay)[ $duration ](bg:overlay)'
show_milliseconds = false

[status]
disabled = false
format = '[ ❯ ](bold text)[ $symbol ](bg:love fg:overlay)[( $common_meaning)( $signal_name) ](bg:overlay fg:love)'
map_symbol = true
pipestatus = true
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = '󰂭'
not_found_symbol = '󰍉'
sigint_symbol = '󰐊'
signal_symbol = '󱐋'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯❯❯](bold fg:pine)'
error_symbol = '[❯❯❯](bold fg:love)'
vimcmd_symbol = '[❮❮❮](bold fg:iris)'
